name: Hourly Weather Update

on:
  schedule:
    - cron: '23 * * * *' # Runs at 23 minutes past the hour to avoid traffic
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib

      - name: Run weather script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python weather_app1.py

      - name: Commit and push changes
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@github.com"
          git add -A
          git commit -m "Hourly update" || echo "No changes"
          git push

      - name: Install dependencies
        run: sudo apt-get install -y xvfb

      - name: Run Weather App
        run: xvfb-run python weather_app1.py
