name: Update Weather Forecast

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R  # This will show us exactly what the file is named in the logs

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas numpy matplotlib meteostat scikit-learn

      - name: Run script
        # We use ./ to tell it to look in the current folder
        run: python weather_app1.py 

      - name: Commit and push chart
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@github.com"
          git add nelson_forecast.png
          git commit -m "Update weather chart" || exit 0
          git push
